/**
 * Prefer English marketplace titles from RealTrack / eBay Motors US payloads.
 */
export function extractEnglishTitle(listing: any): string {
  const candidates = [
    listing?.titleEn,
    listing?.englishTitle,
    listing?.localizedTitles?.en,
    listing?.localizedTitles?.EN,
    listing?.titles?.en,
    listing?.titles?.EN,
    listing?.marketplaceTitle,
    listing?.title,
  ];

  for (const c of candidates) {
    if (typeof c === 'string' && c.trim()) return c.trim();
  }
  return 'Unknown Part';
}

/**
 * Non-English automotive terms (Italian / French / German / Spanish) that
 * RealTrack SalvageA eBay US listings are titled in. RealTrack exposes no
 * `titleEn` field, so the only way to keep the marketplace English-only is to
 * skip listings whose title is written in another language.
 *
 * Matching strategy (German is the hard case):
 * - German glues stems into compound nouns with no spaces ("Halterung",
 *   "Seitenscheibe", "Radhaus"…). Whole-word boundaries never match those, so
 *   German-specific stems are matched by SUBSTRING containment. None of these
 *   stems appear inside English auto-parts vocabulary, so substring matching
 *   has no false positives.
 * - A handful of German stems overlap English words (rad→radiator/radio,
 *   feder→federated, stabil→stabilizer, quer→query). Those are matched as
 *   WHOLE WORDS only so valid English titles survive.
 * - Italian / French / Spanish do not compound, so they stay whole-word.
 * - Any ä/ö/ü/ß (German umlaut / Eszett) is an near-certain German marker and
 *   rejects the title outright — covers compounds the stem list can't reach.
 */

// Umlaut-free (or ASCII-transliterated) German automotive stems/compounds.
// Substring-matched (case-insensitive). Pure ASCII so `includes` needs no
// normalization; accented compounds (Stoßstange, Kühl…) are caught by the
// umlaut pre-check below, so only the transliterated forms belong here.
const GERMAN_SUBSTRING_TERMS = [
  // Umlaut-free compounds seen in live eBay US feeds
  'aschenbecher',
  'bremsleitung',
  'einstiegsleiste',
  'kabelbinder',
  'dichtband',
  'schutzring',
  'kugellager',
  'halteklemme',
  'kantenschutz',
  'sitzkissenbezug',
  'sitzpolster',
  'armlehnenbezug',
  'popniete',
  'klemmplatte',
  'radhaus',
  'innenspiegel',
  'federbein',
  'halterung',
  'armaturenbrett',
  'seitenscheibe',
  'spannfeder',
  'riegel',
  'seitenschweller',
  'heckspoiler',
  'seitenmarkierung',
  'seitenmarkierungsleuchte',
  'kennzeichen',
  'kennzeichenbeleuchtung',
  'innenraum',
  'innenverkleidung',
  'klimaanlage',
  'klimakompressor',
  'kuehlergrill',
  'kuehlmittel',
  'kuehlmittelschlauch',
  'kuehler',
  'luefter',
  'luefterrad',
  'waermetauscher',
  'ventildeckel',
  'zahnriemen',
  'keilriemen',
  'schaltknauf',
  'handschuhfach',
  'mittelkonsole',
  'instrumententafel',
  'sicherheitsgurt',
  'gurtstraffer',
  'fensterheber',
  'dachhimmel',
  'schiebedach',
  'verkleidung',
  'abdeckung',
  'dichtung',
  'lueftung',
  'blende',
  'leiste',
  'halteclip',
  'befestigungsclip',
  'klammer',
  'distanzstueck',
  'fuehrungsschiene',
  'fuehrungs',
  'leitung',
  'kabel',
  'stecker',
  'steckverbinder',
  'rohr',
  'schlauch',
  'luftschlauch',
  'wasserschlauch',
  'tuergriff',
  'kofferraum',
  'tuerschloss',
  'tuerverkleidung',
  'manschette',
  'faltenbalg',
  'wellrohr',
  'gleitlager',
  'lagerbock',
  'achslenker',
  'achszapfen',
  'stuetzlager',
  'stuetz',
  'gleitfuehrung',
  'stellhebel',
  'stellglied',
  'heckklappe',
  'abschlepp',
  'radhausverkleidung',
  'radlauf',
  'radlaufverkleidung',
  'unterbodenschutz',
  'thermostatgehaeuse',
  'oeldruckanzeige',
  'oelkuehlgehaeuse',
  'zuendschloss',
  'zuendkappe',
  'kraftstofftank',
  'kraftstofffilter',
  'kraftstoffdruck',
  'sicherungskasten',
  'anlasserkurbel',
  'anlasserrelais',
  'drosselklappe',
  'drosselklappengehaeuse',
  'ansaugkruemmer',
  'ansaugrohr',
  'ansaugstutzen',
  'ladeluftkuehler',
  'ladeluftrohr',
  'ladeluftschlauch',
  'ladedruck',
  'abgaskruemmer',
  'abgasrohr',
  'abgasanlage',
  'endschalldaempfer',
  'vorschalldaempfer',
  'partikelfilter',
  'dieselpartikelfilter',
  // Core German auto vocabulary (umlaut-free / transliterated stems)
  'getriebe',
  'schaltung',
  'schaltgetriebe',
  'automatikgetriebe',
  'kupplung',
  'differenzial',
  'antriebswelle',
  'gelenkwelle',
  'kardanwelle',
  'kurbelwelle',
  'nockenwelle',
  'pleuelstange',
  'pleuel',
  'zylinder',
  'zylinderkopf',
  'kolben',
  'nocken',
  'kurbel',
  'einspritz',
  'einspritzpumpe',
  'einspritzduese',
  'einspritzventil',
  'kraftstoff',
  'kraftstoffpumpe',
  'kraftstoffschlauch',
  'luftfilter',
  'luftfiltergehaeuse',
  'oelkuehler',
  'oelfilter',
  'oelpumpe',
  'oeldruck',
  'oelschlauch',
  'bremsscheibe',
  'bremse',
  'bremssattel',
  'bremsbelag',
  'bremsschlauch',
  'bremstrommel',
  'bremszylinder',
  'handbremse',
  'feststellbremse',
  'bremslicht',
  'lenkrad',
  'lenksaeule',
  'lenkgetriebe',
  'lenkstockhebel',
  'lenker',
  'schaltgestaenge',
  'kupplungsnehmer',
  'kupplungsgeber',
  'anlasser',
  'lichtmaschine',
  'zuendkerze',
  'zuendspule',
  'zuendkabel',
  'zuendverteiler',
  'zuend',
  'auspuff',
  'auspuffkruemmer',
  'endtopf',
  'katalysator',
  'abgas',
  'kruemmer',
  'stossstange',
  'stossdaempfer',
  'stossfaenger',
  'schraubenfeder',
  'daempfer',
  'schallabsorber',
  'motorhaube',
  'kotfluegel',
  'kotfl',
  'seitenspiegel',
  'rueckspiegel',
  'aussenspiegel',
  'ruecklicht',
  'rueckleuchte',
  'scheinwerfer',
  'nebellampe',
  'nebelleuchte',
  'scheinwerferreinigung',
  'wasserpumpe',
  'wasserpumpenrad',
  'tuer',
  'schenkel',
  'buchse',
  'huelse',
  'nabe',
  'achse',
  'schiene',
  'stoss',
  'schweller',
  'unterboden',
  'sicherung',
  'relais',
  'schalter',
  'schloss',
  'innen',
  'spange',
  'klemme',
  'schelle',
  'riemen',
  'gurt',
  'schnalle',
  'oese',
  'knopf',
  'hebel',
  'schwungrad',
  'drehzahlmesser',
  'drehzahl',
  'drossel',
  'ladeluft',
  'lambdasonde',
  'sonde',
  'harnstoff',
  'adblue',
  'gehaeuse',
  'deckel',
  'kappe',
  'sockel',
  'stuetze',
  'traeger',
  'aufnahme',
  'fuehrung',
  'stellschraube',
  // rad-* compounds (bare "rad" overlaps English radiator/radio → word-boundary)
  'radhaus',
  'radnabe',
  'radlager',
  'radlauf',
  'radkappe',
  'radbolzen',
  'radlenker',
  'radfeder',
  'radhausverkleidung',
  'radabweiser',
  'radbremszylinder',
];

// German stems that overlap English words — whole-word only so
// "Radiator"/"Radio"/"Radar"/"Federated"/"Stabilizer"/"Query"/"Halter"/
// "Hinterland" stay valid English auto titles.
const GERMAN_WORD_TERMS = [
  'rad',
  'feder',
  'lager',
  'stabil',
  'quer',
  'halter',
  'hinter',
  'vorder',
  'gebraucht',
];

// Italian / French / Spanish automotive terms — whole-word only (these
// languages do not form compounds, so boundaries are reliable).
const NON_ENGLISH_WORD_TERMS = [
  // Italian
  'albero',
  'coperchio',
  'pompa',
  'altoparlante',
  'sterzo',
  'cinghia',
  'motore',
  'anteriore',
  'posteriore',
  'destra',
  'sinistra',
  'volant',
  'modanatura',
  'passaruota',
  'pannello',
  'bilanciere',
  'occasion',
  'schermo',
  'portiera',
  'cofano',
  'parafango',
  'sospension',
  'frenata',
  'cremagliera',
  'pignone',
  'biella',
  'boccola',
  'raccordo',
  'regolazione',
  'rinforzo',
  'comando',
  'braccio',
  'inferiore',
  'superiore',
  'raccolta',
  'iniezione',
  'secondaria',
  'trasmissione',
  'accessori',
  'termostato',
  'cuscino',
  'paraurti',
  'specchio',
  'fanale',
  'asse',
  'cambio',
  'scatola',
  'tubo',
  'olio',
  'acqua',
  'montante',
  'cuscinetto',
  'ammortizzatore',
  'tirante',
  'barra',
  'ponte',
  'differenziale',
  'semiass',
  'giunto',
  'omocinetico',
  'scudo',
  'predellino',
  'maniglia',
  'chiusura',
  'serratura',
  'cassetto',
  'plancia',
  'cruscotto',
  'climatizzatore',
  'compressore',
  'alternatore',
  'motorino',
  'centralina',
  'sensore',
  'sonda',
  'lambdasonda',
  'candeletta',
  'bobina',
  'cavo',
  'fusibile',
  'relè',
  'relais',
  'pompetta',
  'collettore',
  'aspirazione',
  'scarico',
  'marmitta',
  'silenzioso',
  'longherone',
  'traversa',
  'parabrezza',
  'lunotto',
  'finestrino',
  'vetrino',
  'vetro',
  'retrovisore',
  'retrovisori',
  'specchietto',
  'condotto',
  'quadro',
  'strumenti',
  'presa',
  'bocchettone',
  'bocchetta',
  'flusso',
  'miscela',
  'soffietto',
  'mantice',
  'convogliatore',
  'deflettore',
  'paraschizzi',
  'paraspruzzi',
  'copertura',
  'supporto',
  'copripavimento',
  'guarnizione',
  'ginocchiere',
  'bracciolo',
  'posacenere',
  'copribracciolo',
  'tappeto',
  'piastra',
  'adattatore',
  'distintivo',
  'terminale',
  'staffa',
  'sportello',
  'pedana',
  'portafusibile',
  'alloggiamento',
  'attacco',
  'misuratore',
  'portata',
  'tappo',
  'sostegno',
  'protezione',
  'rivestimento',
  'autoadesivo',
  'imbottitura',
  'sedile',
  'fascetta',
  'stringitubo',
  'fodera',
  'sottoscocca',
  'pedale',
  'freno',
  'isolamento',
  'acustico',
  'bullone',
  'svasato',
  'esagonale',
  'ruota',
  'telaio',
  'schienale',
  'guscio',
  'carena',
  'carenatura',
  'griglia',
  'mascherina',
  'calandra',
  'fascione',
  'listello',
  'cornice',
  'portellone',
  'portone',
  'baule',
  'vano',
  'sfiato',
  // French
  'roue',
  'pneu',
  'capot',
  'pare',
  'choc',
  'essu',
  'glace',
  'rétroviseur',
  'rétroviseurs',
  'phares',
  'pare-brise',
  'hayon',
  'aile',
  'rotule',
  'roulement',
  'bague',
  'durit',
  'refroid',
  'clim',
  'ventil',
  'allume',
  'démarr',
  'altern',
  'batterie',
  'frein',
  'amort',
  'ressort',
  'coupelle',
  'biellette',
  'essieu',
  'triangul',
  'bercage',
  'flasque',
  'moyeu',
  'cardan',
  'homociné',
  'boîte',
  'boite',
  'embrayage',
  'vilebrequin',
  'soupape',
  'injecteur',
  'carburant',
  'échappement',
  'silencieux',
  'catalyseur',
  'disque',
  'étrier',
  'étriers',
  'plaquette',
  'tambour',
  'amortisseur',
  'ressorts',
  'stabilisatrice',
  'crémaillère',
  'triangle',
  'pare-chocs',
  'parechoc',
  'caisse',
  'indicateur',
  'changement',
  'vitesse',
  'automatique',
  'manuelle',
  'clignotant',
  'portière',
  'coffre',
  'banquette',
  'garnissage',
  'habitacle',
  'commodo',
  'sélecteur',
  'boîtier',
  'calculateur',
  'carburateur',
  'allumage',
  'culasse',
  'démarreur',
  'différentiel',
  'butée',
  'jante',
  'pneumatique',
  'tableau',
  'commande',
  'cylindre',
  'pédale',
  'phare',
  'feu',
  'siège',
  'levier',
  'capteur',
  'bougie',
  'câble',
  'radiateur',
  'refroidissement',
  'climatisation',
  'compresseur',
  // Spanish
  'rueda',
  'neumático',
  'parachoques',
  'paragolpes',
  'espejo',
  'farol',
  'guardabarro',
  'aleta',
  'puerta',
  'maletero',
  'cofre',
  'volante',
  'dirección',
  'amortiguador',
  'muelle',
  'suspensión',
  'mangueta',
  'rótula',
  'rodamiento',
  'embrague',
  'cigüeñal',
  'inyector',
  'filtro',
  'silenciador',
  'pinza',
  'pastilla',
  'cubierta',
  'manillar',
];

// Lookarounds on `\p{L}` instead of `\b`: accented terms ("relè", "étrier",
// "rétroviseur") sit outside the ASCII word class, so `\b` would never match.
const WORD_BOUNDARY_RE = new RegExp(
  `(?<!\\p{L})(?:${[...GERMAN_WORD_TERMS, ...NON_ENGLISH_WORD_TERMS].join('|')})(?!\\p{L})`,
  'iu',
);

/** Scripts that are never an English marketplace title (CJK, Cyrillic, Greek, Arabic, Hebrew). */
const NON_LATIN_SCRIPT_RE =
  /[\u0370-\u03ff\u0400-\u04ff\u0590-\u05ff\u0600-\u06ff\u3000-\u30ff\u4e00-\u9fff\uac00-\ud7af]/;

/** German umlaut / Eszett — a near-certain German marker (rejects outright). */
const GERMAN_UMLAUT_RE = /[äöüß]/i;

/** True when the title reads as English (Latin script, no foreign automotive terms). */
export function looksLikeEnglishTitle(title: string): boolean {
  const value = String(title ?? '').trim();
  if (!value) return false;
  if (NON_LATIN_SCRIPT_RE.test(value)) return false;
  const lower = value.toLowerCase();
  if (GERMAN_UMLAUT_RE.test(lower)) return false;
  for (const term of GERMAN_SUBSTRING_TERMS) {
    if (lower.includes(term)) return false;
  }
  return !WORD_BOUNDARY_RE.test(value);
}
